/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Parameters for scanning a block range for shielded transactions.
 *
 * The UFVK must be obtained from the Ledger device — never derive it from
 * a seed phrase directly in this layer.
 */
export interface SyncParams {
  /** gRPC endpoint URL (e.g. `"https://zaino-zec-testnet.nodes.stg.ledger-test.com/"`). */
  grpcUrl: string;
  /** Unified Full Viewing Key (UFVK) for the account to scan. */
  viewingKey: string;
  /** First block height to scan (inclusive). */
  startHeight: number;
  /** Last block height to scan (inclusive). */
  endHeight: number;
  /** `"mainnet"` or `"testnet"` (default: `"testnet"`). */
  network?: string;
  /**
   * When `true`, Sapling outputs are stripped before trial decryption.
   * Only Orchard actions are processed — eliminates all Sapling crypto work.
   * Set to `true` for Ledger wallets (Orchard-only support).
   */
  orchardOnly?: boolean;
  /**
   * Maximum retry attempts per range on transient errors (timeout, 503).
   * The failing range is split in half on each retry. Defaults to 3.
   */
  maxRetries?: number;
  /** Emit per-phase timing diagnostics to stderr every 10 seconds. */
  verbose?: boolean;
  /**
   * Hex-encoded nullifiers of notes received in previous scans that are still
   * unspent. Enables spent detection across incremental sync boundaries.
   */
  knownNullifiers?: Array<string>;
}
/**
 * A single shielded note found during decryption.
 *
 * Shared between Orchard and Sapling. The spending fields (`nullifier`,
 * `rseed`, `cmx`, `position`, `recipient`) are Orchard-specific and `None`
 * for Sapling notes. A dedicated Sapling type is deferred until Sapling
 * spending is needed.
 */
export interface ShieldedNote {
  /** Amount in zatoshis (f64 for JS Number compatibility). */
  amount: number;
  /** `"incoming"`, `"outgoing"`, or `"internal"`. */
  transferType: string;
  /** Memo text decoded from the note. */
  memo: string;
  /** Orchard nullifier (64-char hex = 32 bytes). Used for spent detection and PCZT. */
  nullifier?: string;
  /** rho value (64-char hex = 32 bytes). Required with rseed for Note::from_parts. */
  rho?: string;
  /** Random seed (64-char hex = 32 bytes). Required for spending. */
  rseed?: string;
  /** Extracted note commitment cmx (64-char hex = 32 bytes). Required for Merkle witness. */
  cmx?: string;
  /**
   * Leaf position in the Orchard commitment tree (decimal string).
   * None when ChainMetadata is absent.
   * String avoids f64 precision loss on u64 -> f64 -> u64 round-trips.
   */
  position?: string;
  /** Recipient bytes (86-char hex = 43 bytes: 11-byte d + 32-byte pk_d). For note reconstruction. */
  recipient?: string;
  /** True if this note was spent in a later block within the scanned range. */
  isSpent: boolean;
}
/** A matched and fully-decrypted shielded transaction. */
export interface ShieldedTransaction {
  /** Transaction ID in big-endian (display) hex order. */
  txid: string;
  /** Raw transaction bytes as a hex string. */
  hex: string;
  /** Block height at which this transaction was confirmed. */
  blockHeight: number;
  /** Block hash in big-endian (display) hex order. */
  blockHash: string;
  /** Block timestamp (Unix seconds). */
  blockTime: number;
  /** Transaction fee in zatoshis (shielded bundles only). */
  fee: number;
  /** Decrypted Sapling notes belonging to this account. */
  saplingNotes: Array<ShieldedNote>;
  /** Decrypted Orchard notes belonging to this account. */
  orchardNotes: Array<ShieldedNote>;
}
/** Scan statistics returned once the stream is exhausted. */
export interface SyncStats {
  blocksScanned: number;
  elapsedMs: number;
  /**
   * Hex-encoded nullifiers from `knownNullifiers` that were spent in the scanned range.
   * JS uses this to mark previously-stored notes as spent.
   */
  spentKnownNullifiers: Array<string>;
}
/**
 * Start scanning a range of compact blocks and return a transaction stream.
 *
 * The scan runs in the background immediately. Call `stream.next()` to
 * consume transactions as they are found. Call `stream.stats()` after the
 * stream is exhausted to retrieve scan statistics.
 *
 * Trial decryption runs entirely in Rust (no JS event loop blocking).
 * `GetTransaction` is called only for matched transactions.
 */
export declare function startSync(
  params: SyncParams,
): Promise<TransactionStream>;
/** Returns the current chain tip height from the gRPC endpoint. */
export declare function getChainTip(grpcUrl: string): Promise<number>;
/**
 * Find the block height closest to the given Unix timestamp via interpolation search.
 *
 * Returns the height of the latest block whose timestamp is ≤ the target.
 * If the timestamp is before genesis, returns the genesis height.
 * If the timestamp is after the chain tip, returns the tip height.
 */
export declare function findBlockHeight(
  grpcUrl: string,
  timestamp: number,
): Promise<number>;
export interface OrchardSpendInputJs {
  /** 86-char hex (43 bytes: 11-byte diversifier + 32-byte pk_d). */
  recipient: string;
  /** Decimal u64 (string to avoid f64 precision loss). */
  valueZat: string;
  /** 64-char hex (32 bytes). */
  rho: string;
  /** 64-char hex. */
  rseed: string;
  /** 64-char hex. */
  cmx: string;
  /** Decimal u64 leaf position in the Orchard commitment tree. */
  position: string;
}
export interface OutputRequestJs {
  /**
   * Destination address: t-addr (P2PKH/P2SH) or u-addr (Orchard receiver).
   * Sapling z-addresses and TEX (ZIP-320) addresses are rejected.
   */
  address: string;
  valueZat: string;
  memo?: string;
}
/** One transparent (P2PKH) UTXO to spend. */
export interface TransparentInputJs {
  /**
   * 64-char hex (32 bytes) prevout txid in internal (little-endian) byte order.
   * Ledger Live surfaces txids in display (big-endian) order; callers must
   * reverse before passing.
   */
  txid: string;
  /** Output index within the origin transaction. */
  vout: number;
  /** Hex-encoded raw scriptPubKey bytes (no CompactSize length prefix). */
  scriptPubkey: string;
  /** UTXO value in zatoshis (decimal string to avoid f64 precision loss). */
  valueZat: string;
  /** 66-char hex (33 bytes) compressed secp256k1 pubkey controlling the UTXO. */
  pubkey: string;
}
export interface BuildTransactionParams {
  grpcUrl: string;
  ufvk: string;
  network?: string;
  /**
   * 64-char hex (32 bytes): ZIP-32 seed fingerprint of the wallet seed,
   * read from the device. Stamped onto each real spend so the device can
   * confirm the PCZT belongs to its seed before signing.
   */
  seedFingerprint: string;
  /** ZIP-32 account index the UFVK was derived at. */
  accountIndex: number;
  /**
   * Caller-owned fee in zatoshis (decimal string to avoid f64 precision
   * loss). Per FR-4 the fee is selected by ledger-live; this
   * crate validates it against ZIP-317 and derives change from it rather
   * than computing a fee itself.
   */
  feeZat: string;
  spends: Array<OrchardSpendInputJs>;
  /** Transparent (P2PKH) UTXOs to spend. Empty for Private→* flows. */
  transparentInputs: Array<TransparentInputJs>;
  outputs: Array<OutputRequestJs>;
  anchorHeight?: number;
}
export interface BuildTransactionResult {
  /**
   * Hex-encoded canonical PCZT bytes (`PCZT` magic + u32 LE version +
   * postcard payload). Ready for the device APDU streaming layer. Carries
   * each real spend's ZIP-32 derivation path for on-device signing.
   */
  pcztHex: string;
  /** Decimal fee in zatoshis. */
  feeZat: string;
  /** Block height the Merkle paths were computed against. */
  anchorHeight: number;
  /** Orchard action count after dummy padding. */
  nActionsOrchard: number;
  /** Transparent input count. */
  nTransparentInputs: number;
  /** Transparent output count (including change). */
  nTransparentOutputs: number;
}
/**
 * Build, prove, and serialize a PCZT for a send transaction.
 *
 * Supports Orchard-source (Private→*) and transparent-source (Public→*)
 * flows. Halo 2 proof generation happens here for Orchard-bundle transactions
 * (~2-5 s first call, ~hundreds of ms thereafter thanks to the process-global
 * ProvingKey cache). Transparent-only transactions skip the Orchard prover.
 */
export declare function buildTransaction(
  params: BuildTransactionParams,
): Promise<BuildTransactionResult>;
/**
 * Async iterator over matched shielded transactions.
 *
 * Usage (TypeScript):
 * ```ts
 * const stream = await startSync(params);
 * let tx: ShieldedTransaction | null;
 * while ((tx = await stream.next()) !== null) {
 *   console.log(tx);
 * }
 * const stats = await stream.stats();
 * ```
 */
export declare class TransactionStream {
  /**
   * Returns the next matched transaction, or `null` when the scan is complete.
   *
   * # Safety
   *
   * napi-rs requires `unsafe` for `&mut self` in async methods.
   * This method is safe to call — it only mutates the internal channel receiver.
   */
  next(): Promise<ShieldedTransaction | null>;
  /**
   * Cancels the background scan immediately.
   *
   * Aborts the tokio task running the sync engine. Any buffered transactions
   * already sent by Rust are still consumable via `next()`, which will then
   * return `null` once the buffer is drained. `stats()` will return an error
   * after cancellation.
   */
  cancel(): void;
  /**
   * Returns scan statistics once the stream is exhausted (i.e. after `next()`
   * returns `null`). Calling this before the stream is done will wait until
   * the background sync task finishes.
   *
   * # Safety
   *
   * napi-rs requires `unsafe` for `&mut self` in async methods.
   */
  stats(): Promise<SyncStats>;
}
